### ISSUE TITLE
Regex Error in Validation.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#1]
Validation.h's private regex ColorPatterns, is giving an error in instantiation.  Currently what is implemented (string construction) utilizes **ECMAScript**, and instead should be constructed with string and flag, with the flag set for **basic**, to avoid current error. 

Because this error is within the constructor, it is also effecting any other class that calls Validation.h.

**Comment by krs-world** [comment]
Hmmm, dont even remember what I did here.. I need to understand this better,
or I will let you fix it after I push  version to git.

**Comment by dcarmer** [comment]
Yes it was a runtime error.

It seems though, if the visualization can handle any hexadecimal colors, we should keep its support.

If anything I would have removed the ColorNames, because while they offer an easier form of color input for users, the documentation doesn't specify a list of valid colors. The hexadecimal on the other hand allows the representation of any color and is also commonly understood and well documented on what is valid or not.

**Comment by krs-world** [comment]
I have now integrated the color names and other vis. properties into the 
ElementVisualizer and LinkVisualizer doc pages - so this should take care of it.

You are making an assumption that our sophomores actually know what hexadecimal numbers are! No!  Or RGB colors..  I am sure color names will be easier, with the documentation.

**Comment by dcarmer** [comment]
I don't have a great sense for what most students know or don't know so I'll differ to your judgement, but I would think that most sophomores *would* know the various standards for color specification, such as the hexadecimal (#ffffff) and integer (255,255,255) schemes. And if they don't It seems like this would be a good opportunity to introduce them to it, as I imagine they would need to know it eventually. 

Additionally, while I do understand this isn't a drawing program designed to handle complex sophisticated color and the number of color names in place is more than sufficient, other schemes provide for all colors not just specified ones, and I can't help but think we may be limiting an ambitious user, not to mention ourselves. Should we ever, for instance, see the need for color transparency, it would only require the addition of the alpha channel, while the names would be lacking. 

If we really just want to stick to the names, I'll let it go and close this issue, but I personally would recommend we at least additionally implement the hex or 255 scheme.
