### ISSUE TITLE
Templatization of Edges in GraphAdjList.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#10]
The adjacency List in GraphAdjList.h uses Edge<Key> and instead should be using Edge<E>.

**Comment by krs-world** [comment]
Your comment is confusing. Please clarify.

**Comment by dcarmer** [comment]
My bad, it mistook my template parameters as html tags and made them invisible.

What I meant to say was that unless I'm misunderstanding something,
The adjacency List in GraphAdjList.h uses an *Edge of type key* and instead should be using an *Edge of type E*.

**Comment by krs-world** [comment]
No, it has to be Edge<Key>.

AdjList uses maps and the Key is type to get to the edge vertices; so the source
vertex is sitting in the vertices map and the edges(their terminating vertex) is sitting in the adjacency lists. Both types need to be the same (it can be int, string, etc). So when you define the key to be of type string, both vertices are
accessed using string keys. The edge_data member  inside the Edge data type is to keep any appl. specific data of the graph. Weight of hte edge is kept within
the Edge (similar to Shaffer's implementation).

**Comment by dcarmer** [comment]
Right, my mistake. 
However I believe my confusion stems from the addEdge() method.

It appears to create an Edge of type key using two parameters. The only Edge constructor with two parameters is int weight and Key v, where v represents the destination vertex. But in addEdge(), the edge is created with a int weight (which is correct) and a string representation of the destination vertex, not the vertex itself. Thus GraphAdjList seems like it should only work if the key is a string, as for any other type passing in a string for the key value will be an error.
