### ISSUE TITLE
Key in ElementVisualizer.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#12]
ElementVisualizer.h's setKey() function is not validating the key.

Key doesn't seem to be used and should be implemented or removed.

If implimented, there should likely be a getKey() function, which ElementVisualizer.h is lacking.

**Comment by krs-world** [comment]
Used by BSTElement

**Comment by dcarmer** [comment]
My mistake, I missed the call in BSTElement. 

However, key validation is still not occurring and it still seems like there should be a getKey function.

**Comment by krs-world** [comment]
This is used only for the JSON creation convenience (updated the docs a bit more). As to validation, it has to be a string coming in - this should be flagged by the compiler if its something else..  what other validation is needed?

I put this function here for convenience, I will see if this can be moved.

**Comment by dcarmer** [comment]
Oh okay.

Well as far as validation goes, if all it needs to be is a string than it doesn't even need the try/catch block, because as you said, the compiler will flag it.

But I was assuming, since the comments say something to the effect that it's supposed to be an orderable converted to a string, as well as the commented out key validation call, that you wanted to do some extra verification on the key.
