### ISSUE TITLE
Invalid pointer potential in Element.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#16]
In Element.h's getLinkVisualizer() function, if a bad_alloc occurs it returns null without actually fixing the error, potentially leading to a subsequent call giving undefined behavior.

Shouldn't return null, instead, set the value to null and return like normal.

**Comment by krs-world** [comment]
the createion of ElementVisualizer() and LinkVisualizer () are within try/catch
blocks (bad alloc). Do we need to do anything further?

**Comment by dcarmer** [comment]
getLinkVisualizer() looks good, but the error persists in the constructor.

The new operator will rarely be unable to allocate memory. **There are numerous places where new is called without a try catch, but as it can significantly clutter code with every new call, catching is usually not done.**

That being said, when putting new in a try/catch block, it is being acknowledged that it may throw **bad_alloc** and subsequently if it does throw, the pointer will be left uninitialized.

Since you are bothering to catch here, and you're not exiting if caught, the pointers that have failed to be allocated should be initialized to null to prevent undefined behavior.

**Comment by dcarmer** [comment]
If your intention is to put each new operator call in a try catch, then there are a few that still need to be caught, in graphAdjList and Matrix.

 I'll need to check everything again to make sure I'm not forgetting any others.

**Comment by dcarmer** [comment]
If the program should be allowed to continue and you don't intend to exit, in the event of a bad alloc, to reduce clutter and ensure initialization, you could use the no-throw version of the new operator which will return null if it fails, instead of throwing an error.
