### ISSUE TITLE
Static variable in Element.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#17]
Element.h's static int ids variable could be defined **within the class** for extra readability, instead or outside the class by itself.

**Comment by krs-world** [comment]
It IS defined inside the class. The outside definition at the end of the class is 
its allocation (it is allocated once, not with every instantiation of the clas) - see
the private section of the class.

**Comment by dcarmer** [comment]
My mistake, I've done more research. I wasn't aware that in C++ static members must be initialized outside the class
