### ISSUE TITLE
Assignment Operator calls constructor in Element.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#18]
Element.h's assignment operator is calling the constructor, though it is unnecessary and increases the static id variable.

This call should be removed.

**Comment by krs-world** [comment]
This is an issue I still dont understand very well (copy constructors). Here the main
thing is that we cannot have two elements with the same id. Else it will break BRIDGES. We need to look into this issue of doing the copy constructor right.

Need to revisit this issue.

**Comment by dcarmer** [comment]
Yeah, I'm still learning the intricacies of C++. To understand assignment operators I used this [site](http://www.icu-project.org/docs/papers/cpp_report/the_anatomy_of_the_assignment_operator.html). I thought it was very detailed and comprehensive.

Essentially in summary, *copy constructors and assignment operators are two different things*. Assignment operators such as this, do not actually create a new object, but rather just modify the data of an existing object, much like any other function could. That being said to have objects using the assignment operator they must already have been created with a constructor, and therefore will have unique ids. The constructor call in the assignment operator really isn't effecting anything other than arbitrarily increasing the static id variable.

**Comment by krs-world** [comment]
Ah.. you are right.. fixed.. I was confusing between the two.

**Comment by dcarmer** [comment]
Looks good
