### ISSUE TITLE
std::out called in Connector.h's post

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#20]
With a successful curl post in Connector.h, curl prints directly to std::out, bypassing cout. This leads to an unavoidable info dump into the standard output, likely disgruntling users. 

To prevent this cluttering of std::out, CURLOPT_WRITEDATA should be set in some way.

**Comment by krs-world** [comment]
I will need to look into this.  Does this go into a file? Is that what we want the
user to see? Is that useful?  Need a more friendly solution.

**Comment by dcarmer** [comment]
std::out just goes into where ever standard output is defined by the environment, so for most people just the console. 
The CURLOPT_WRITEDATA can instead be set to direct the data to anywhere, from a file, to something like standard output for logging(clog) *(I would recommend this)*, or even just into the abyss since we don't need it for anything other than potential debugging right now.

The data returned is very messy and unnecessary for standard users, so I don't see any reason they would need it.

**Comment by krs-world** [comment]
This is fine, but only if the post fails, then you can expect any details of this to come back through it.. when there are other errors, how do you catch those into 
a file. This is the issue I am investigating and have also asked Mihai/David to look into a more robust solution. One possibility is to trap that in the server and translate it into something simpler and meaningful to the user's console - if that can be done, thats a good solution.
