### ISSUE TITLE
Documentation using triple slash

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#25]
GraphAdjMatrix.h and GraphAdjList.h's documentation uses *triple slashes*, instead of *slash star*.

In GraphAdjMatrix.h, one line has a missing slash, leaving out from the documentation.

This should be replaced with *slash star*.

**Comment by krs-world** [comment]
All comments replaced by  /**  */  style.. good to double check after the next push.

**Comment by dcarmer** [comment]
Looks good
