### ISSUE TITLE
Unneeded try/catches in Bridges.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#27]
In Bridges.h several functions contain try/catch blocks for a manual throw. With the if block already determining if the error is present, it seems redundant to place it all in an additional try/catch block. Anything that you have after the throw could just be put in an else block instead.  

The try/catch blocks should be removed, with the catch statement(s) put in the __if__ block and with the remainder of the try statement(s) put in the __else__ block.

**Comment by krs-world** [comment]
You are right.. I took the try/catch blocks out.. modified so that visualize () does nothing if the data structure handle is null.

**Comment by dcarmer** [comment]
Looks good
