### ISSUE TITLE
Lacking null checks in Bridges.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#28]
Several functions in Bridges.h check their input isn't null, but others are missing such checks.

setDataStrucutute(Element*, int) doesn't check if Element is null
setDataStrucutute(GraphAdjList*, int) doesn't check if GraphAdjList is null
setDataStrucutute(GraphAdjMatrix*, int) doesn't check if GraphAdjMatrix is null

**Comment by krs-world** [comment]
Fixed.. now the execution continues in the 'try' block if the DS is non-null, else
sets the DS type to 'None' and the visualize() method outputs a message.

**Comment by dcarmer** [comment]
Looks good
