### ISSUE TITLE
Unnecessary casting in Bridges.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#29]
In Bridges.h several setDataStructure() functions unnecessary cast their input as themselves.
Ex: 
__function(SLelement<E>* head)
{
   ...stuff...
   root = (SLelement<E>*) head;
}__

This is redundant and should be excluded.

**Comment by krs-world** [comment]
These have been fixed.. they all needed to be be cast to Element<E> * and I 
now use static_cast< > to do that. We are doing upcasting  so that we can use
the same handle to the different data structures (for the lists and trees)

**Comment by dcarmer** [comment]
Pointers can be up-cast implicitly, so I believe the static_cast<> calls are also unnessasary

**Comment by krs-world** [comment]
You are right. Done.

**Comment by dcarmer** [comment]
Looks good
