### ISSUE TITLE
Not Destructor for GraphAdjMatrix.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#3]
GraphAdjMatrix.h owns pointers and is lacking a destructor to delete them.

**Comment by krs-world** [comment]
Great, I will start looking at all these issues and push new versions of 
the code to git.. and you
can test again..

     -- krs


On 11/7/15 3:34 AM, dcarmer wrote:
>
> GraphAdjMatrix.h owns pointers and is lacking a destructor to delete them.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/krs-world/bridges-cxx/issues/3>.
>

-- 
Kalpathi Subramanian                                   Ph: 704 687 8579
Associate Professor                                    Email: krs@uncc.edu
Dept of Computer Science                               Web:http://webpages.uncc.edu/~krs
The University of North Carolina
Charlotte, NC 28202-0001

**Comment by krs-world** [comment]
Fixed.

**Comment by dcarmer** [comment]
GraphAdjMatrix.h seems to still not have a destructor.

**Comment by krs-world** [comment]
Fixed.

**Comment by dcarmer** [comment]
Looks good
