### ISSUE TITLE
Bridges.h incorrect throw documentation

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#30]
Several functions in Bridges.h are documented as throwing exceptions, when they do not.

The documentation should not indicate that these functions throw.

**Comment by krs-world** [comment]
I think I have fixed all of them.

**Comment by dcarmer** [comment]
setAssignment(int) is still documented as throwing an exception.
If the validation fails, bridges calls exit(EXIT_FAILURE), but this still doesn't throw.

**Comment by krs-world** [comment]
I see a throw in the try block (for catching negative assignment numbers. Wouldnt that be caught in the catch block?

**Comment by dcarmer** [comment]
Yeah, exactly. The function throws internally, but also catches it internally, so for documentation purposes it shouldn't be declared as throwing an exception because it will always catch itself, without actually throwing to the user who is calling it.

And again I would recommend changing it like you have for the others. In that, since you already have a check for the throw, it would be better to put the catch calls in the if statement and leave the remainder in the else, without using a try/catch or manual throw altogether.

**Comment by krs-world** [comment]
removed try/catch in setAssignment

**Comment by dcarmer** [comment]
Looks good, but it is printing the error message to cout. 
This should be changed to cerr, to keep in line with similar situations.

**Comment by krs-world** [comment]
fixed.

**Comment by dcarmer** [comment]
setAssignment still seems to be printing to cout not cerr. Additionally Bridges.h's server error msg functions are also printing to cout instead of cerr.

**Comment by krs-world** [comment]
fixed.

**Comment by dcarmer** [comment]
visualize is still using cerr

Also since this is an if else list, I would exclude the explicit "None" check and just leave its code in an else statement at the end, that way if for some odd reason the visualizer type is not one of these types it will still be handled.
