### ISSUE TITLE
Redundant pointers in Bridges.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#31]
Bridges.h contains two Element<E>*, one named root and another array_list.
As I understand it, only one of these pointers is ever used at a time as decided when set, so having two seems unnecessary when the same pointer could hold either data.

These should be consolidated into one Element<E> pointer.

**Comment by krs-world** [comment]
Good catch. I have fixed. Will push a new version only after my first round of fixes.

**Comment by dcarmer** [comment]
Looks good
