### ISSUE TITLE
Use switch instead of if else in Bridges.h's visualize()

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#32]
There is a long if else chain in Bridges.h's visualize function that could be replaced by a switch statement, since the list of choices are string constants. 

Also instead of calling so many different helper functions, the functionality should be in visualize(). Most of these helper functions have similar calls, which would reduce the chance for errors and improve readability if they were called in __one place within visualize()__ instead of within each helper, with the __unique material residing in the switch block__.

**Comment by krs-world** [comment]
Cannot do switch with std::string  -- switch must evaluate to an integer. 

I wanted to do this, but didnt find a simple way to do this.

**Comment by dcarmer** [comment]
My mistake, I didn't realize the condition of a switch needed to be able to be implicitly converted to an integer.

However, much of the code within the helper functions is similar and it still seems like condensing it into the visualize() function would be beneficial.

**Comment by krs-world** [comment]
My plan is to bring the color names to the docs. It would also be good 
to have a RGB  (all from 0-1 scale)
as a method, if its easily doable. But having a bunch of colors is more 
than adequate for this
application.

I totally agree that students will be lost in terms of color names 
without accompanying docs.

     -- krs


On 11/17/15 2:59 AM, Dakota Carmer wrote:
>
> My mistake, I didn't realize the condition of a switch needed to be 
> able to be implicitly converted to an integer.
>
> However, much of the code within the helper functions is similar and 
> it still seems like condensing it into the visualize() function would 
> be beneficial.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/krs-world/bridges-cxx/issues/32#issuecomment-157303074>.
>

-- 
Kalpathi Subramanian                                   Ph: 704 687 8579
Associate Professor                                    Email: krs@uncc.edu
Dept of Computer Science                               Web:http://webpages.uncc.edu/~krs
The University of North Carolina
Charlotte, NC 28202-0001

**Comment by dcarmer** [comment]
Um, I believe this last comment was meant to be in the regex issue thread, as it doesn't pertain to this one.
