### ISSUE TITLE
ADTVisualizer includes and consts

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#35]
ADTVisualizer.h doesn't need to include TreeElement.h or vector.h

ADTVisualizer also has a collection of strings used for JSON creation that should be made const

**Comment by krs-world** [comment]
Fixed.. ADTVisualizer includes the element classes and Bridges.h just includes ADTVisualizer.h.  The JSON strings are made constant.

**Comment by dcarmer** [comment]
Cool, I wasn't sure if you wanted each header to directly include each file, or if an included file included one that would be enough, but its clear now. 

That's why I would suggest not including TreeElement, as BSTElement is derived from, and therefore includes TreeElement already.

**Comment by krs-world** [comment]
ah yes, updated my version.. I missed that one.

**Comment by dcarmer** [comment]
While we're on the subject, string is included in a multitude of files, so I'm assuming that the paradigm we're using is: We leave out bridges header files that we know are included within other included files, but we also explicitly include c++ libraries in each header that needs it.

If this is the case SLelement, as well as DLelement should include string. If not than I can provide a more specific list of files that are unnecessarily including c++ headers.

**Comment by krs-world** [comment]
Those two files include Element, which includes string.
