### ISSUE TITLE
Bridges.h memory leaks

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#36]
setVisualizer, setRoot, and the setDataStructure functions all set pointers, who may or may not have been set earlier. If bridges owns any of these pointers than it is its own responsibility to delete the old pointers before assigning a new value.

**Comment by krs-world** [comment]
Fixed:

Update: added a destructor to ADTVisualizer (to clear map)
Cleanup called on the lists and trees;  graphs have destructors which will free its allocated structures.

Please recheck to ensure I didnt miss anything.

I am glad you are perusing  the code closely. Thats exactly what we need!

**Comment by dcarmer** [comment]
setDataStructure(SLelement) is casting to DLelement and shouldn't be.

There are several if statements checking if pointers are null, to delete them and this is unnecessary. Calling delete on nullptrs is fully documented, and does nothing, so in an effort to keep code slim, these if checks with nothing but delete within them should be removed leaving just the delete call.

I also understand why you leave it up to the user to handle the array data structures deletion because they created it, but isn't this also true for any of the other data structures. It seems to me that bridges.h should handle the deletion of all/any of them when being overwritten, or none at all.

**Comment by dcarmer** [comment]
I received your email replying to this issue, I'm not sure why they sometimes don't appear on git.

So you asked "where is this?" , but I'm not sure if you were referring to the nullptr checks(throughout bridges) or the DLelement casting(in setDataStructure(SLelement)).

As to the pointer deletion, by all means if you expect the user to still be using the original data structure upon an additional setStructure call, than we shouldn't delete it, leaving it up to the user instead, which is why I recommended only deleting pointers that bridges supposedly owns.

Yes, I like the cleanup functions, as really they are destructors for the entire structure, not just the individual class. However I'm not sure whether they should be static and take in an object, or called on the object itself. I'm leaning toward non-static.

**Comment by dcarmer** [comment]
I actually take back preferring non-static, if we change the cleanup functions to take in a pointer by reference and within set this pointer to null. 
This will help prevent users from trying to use invalid pointers after the cleanup.

**Comment by krs-world** [comment]
Ah, user's responsibility, I think..  passing a pointer to a pointer will be a bit
too complex, I think for sophomore level students? Probably not ready.. i.e.  if you want to set the handle to the DS null.
