### ISSUE TITLE
Bridges cleanup

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#38]
In the cleanup function, it shouldn't return if root is null, as the graphs may still need to be cleaned.

Since the flow is a set of if else's, I'd put the "Array" as the else case.

Also as only one dataStructure is in use at a time and explicit down casting is already in place, you could use a void pointer to hold both the root and graphs.

**Comment by krs-world** [comment]
Fixed..  currently, we are only using 1 data structure at a time -- there has been
some discussion of using multiple DS  in BRIDGES. For instance, an array of linked lists.. lets keep this structure for now. I took out out  the first part of the function that checks the root. Array check moved to the end - probably not needed(just there for completeness/readability).

**Comment by dcarmer** [comment]
Cleanup looks good.

However looking to the potential of having multiple DS in bridges, your example of an array of linked lists still seems like you would have the root to the array set in bridges, while the added support would be put in visualizer type. *In this case having one void pointer would still be applicable.*

**Comment by krs-world** [comment]
So we can just have one void pointer and then cast it to any of the data structure types, based on which one is active? Having multiple data structure would
require keeping a list of data structure handles, it would seem.
