### ISSUE TITLE
Element memory leaks

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#40]
setVisualizer replaces a pointer that may or may not be set already. To prevent memory leaks, the old pointer should be deleted before reassignment.

Additionally the string identifier should be made constant

**Comment by krs-world** [comment]
fixed.

**Comment by dcarmer** [comment]
Since all that is being done is the deletion of the pointer, you might as well forgo the null check, deleting a nullptr does nothing.

Also the identifier still should be a const.

**Comment by krs-world** [comment]
Added a destructor to ElementVisualizer and Element. Need to free up
the visualizer objects. Also ensured any failure of allocation exits BRIDGES.
Removed the pointer check.

Identifier value gets set when the element is created.. if you declare it a const, wont let you assign it in teh constructor(I remember getting a similar compiler error on something related).. isnt that right?
