### ISSUE TITLE
Bridges.h

### ISSUE THREAD

**Issue by dcarmer** [krs-world/bridges-cxx#43]
holds void pointer that casts to proper pointer
Made bridges static(ish)
Switched templated class to templated functions, user must use the same parameters for setDataStruct, and visualize
Added nested class that holds variables. Bridges holds nested object as static to prevent messy static declarations.
Added enum to represent visualizer type
Combined with connector
Holds assignment number as double instead of two ints

**Comment by krs-world** [comment]
Assignment number.. Not a good idea..  we had it as float and had issues 
when sending it to server. Lets keep these
as two ints  for now and if needed can be concatenated later..

     - krs

On 12/6/15 3:18 AM, Dakota Carmer wrote:
>
> holds void pointer that casts to proper pointer
> Made bridges static(ish)
> Switched templated class to templated functions, user must use the 
> same parameters for setDataStruct, and visualize
> Added nested class that holds variables. Bridges holds nested object 
> as static to prevent messy static declarations.
> Added enum to represent visualizer type
> Combined with connector
> Holds assignment number as double instead of two ints
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/krs-world/bridges-cxx/issues/43>.
>

-- 
Kalpathi Subramanian                                   Ph: 704 687 8579
Associate Professor                                    Email: krs@uncc.edu
Dept of Computer Science                               Web:http://webpages.uncc.edu/~krs
The University of North Carolina
Charlotte, NC 28202-0001

**Comment by esaule** [comment]
Seems like this was all processed a while back. Closing.
