### ISSUE TITLE
Bridges initialization.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#47]
This method has the paramters inverted, when compared to the Java version. 

Lets change this to 
Bridges::initialize( assignment_number,  Bridges_user_id, Bridges_API_key)

So that it is consistent. 

(I am working on the user manuals/tutorial pages today, once I finish we will need to modify the impacted examples as well).

**Comment by esaule** [comment]
Correct in the C++ version at the moment.
