### ISSUE TITLE
updates - c++ version..

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#53]
I have added a label to the LinkVisualizer - set/getLabel()

Also modified the graph class to get the link visualizer more directly, such as 

graph.getLinkVisualizer(key1, key2).setThickness( 2.0f)

where key1, key2 reprsents the link nodes.

This should be much simpler for the user. If key1 or key 2 doesnt exist, an error will be thrown.

David, when you have made the server side changes, let me know and I can t est both Java and C++ versions with the new LinkVisualizer labels.

       -- krs

**Comment by krs-world** [comment]
Also in graph you can now do (already in Java version)

graph.getVisualizer(key_val).setColor("red")  would 

set that vertex with the key value to red. 

Should be a much simpler interface for users to set attributes of vertices and links. Exceptions will happen if the vertex or link doesnt exist.

      -- krs

**Comment by esaule** [comment]
This was implemented. a while back on the java version.
