### ISSUE TITLE
changes to graph data type..

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#54]
Have made a number of changes to the graph data type:

1. settng/getting attributes is much simpler, using the getVisualizer(), get LinkVisualizer methods in the graph classes

2. There are now 3 generic parameters to the graph classes, the Key, E1 (for vertex data)  and E2 (edge data).   E1= K, E2= E1   is the default. So now for simple graphs using  strings as keys, you can create the graph as 
GraphAdjList<string>

3. Methods to set/getVertexData(), set/getEdgeData()

4. More robust exception handling for errors (nonexistent vertices, edges).

Similarly GraphAdjMatrix updated. This holds edge data in a separate map, that is transparent to the user.

**Comment by esaule** [comment]
No issue here. Closing.
