### ISSUE TITLE
Grid Changes

### ISSUE THREAD

**Issue by squeetus** [krs-world/bridges-cxx#55]
Modify the C++ version to include the Grid, ColorGrid, and Color representation changes:

Color: https://github.com/squeetus/bridges/commit/0987e97a06372e6c343be44afaddf6445a433fde#diff-e3110be62f206e41343786640d0a9278

Grid: https://github.com/squeetus/bridges/commit/0987e97a06372e6c343be44afaddf6445a433fde#diff-cb5f69d42d3bddf19ba321c4ad28bfec

ColorGrid: https://github.com/squeetus/bridges/commit/0987e97a06372e6c343be44afaddf6445a433fde#diff-b69d251c44b8510588f58ea4bc945fe5

**Comment by krs-world** [comment]
So I can get the C++ version of the grid to work upto 440x440 size. After that it gives me errors from the server (22) for some reason..  I have checked the JSON and it looks right.

The driver is in the Dropbox (under the cxx/Basic subfolder of Bridges_Testing)   -- grid.cpp

The cxx git repo is uptodate..
