### ISSUE TITLE
Map overlay and Coordinate System

### ISSUE THREAD

**Issue by squeetus** [krs-world/bridges-cxx#56]
C++ client needs a quick update to Bridges.h to set map overlay and coordinate system type and add these flags to the JSON. 

Here are some commits from the Java version for reference:
https://github.com/krs-world/bridges/commit/faa517045644db482e5d2e8d13d9089f11b8c290
https://github.com/krs-world/bridges/commit/07f1062595a4f604ede7f24bd62dd66b40f83e89

**Comment by krs-world** [comment]
C++ code updated with the needed functions, but not displaying map on a linked list example.  C++ version will convert to lower case the map options and put that in the JSON - is the server going to read that right?

Json is as follows:

JSON String:	{"visual":"SinglyLinkedList","title":"A Trivial Singly Linked List","description":"In computer science, a linked list is a linear collection of data elements, called nodes, pointing to the next node by means of a pointer. It is a data structure consisting of a group of nodes which together represent a sequence. Under the simplest","coord_system_type":"equirectangular","nodes":[{"color":[0,255,255,1.000000],"shape":"circle","size":10,"name":"0"},{"color":[70,130,180,1.000000],"shape":"circle","size":10,"name":"1"},{"color":[70,130,180,1.000000],"shape":"circle","size":10,"name":"2"},{"color":[70,130,180,1.000000],"shape":"circle","size":10,"name":"3"}],"links":[{"color":[255,0,0,1.000000],"thickness":1,"weight":1,"source":0,"target":1},{"color":[0,0,255,1.000000],"thickness":1,"weight":1,"source":1,"target":2},{"color":[0,255,255,1.000000],"thickness":1,"weight":1,"source":2,"target":3}]}

**Comment by krs-world** [comment]
Code fixed now, but server should accept all lower case for coord system types, it will be more robust. C++ version wont work now, as it converts the name to lower case and checks the 3 types.
