### ISSUE TITLE
array updates.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#63]
New constructors and getValue() changed to getElement (with versions for 1d, 2d and 3d arrays).

**Comment by esaule** [comment]
What is the issue with that?

**Comment by esaule** [comment]
@krs-world I pushed some changes to the array and fixed some bugs. If you have codes for 2D and 3D arrays can you run them to make sure I did not screw up something?

**Comment by esaule** [comment]
@krs-world confirmed it works now.
