### ISSUE TITLE
New data structures..

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#72]
David, add  the following data structure names that the server will recognize - these will all be tree types and will have a representation siimilar to the existing trees:

KdTree
QuadTree

Eric: you mentioned
BTree
B+Tree

Please edit above appropriately.
       -- krs

**Comment by esaule** [comment]
Let's think about that a bit more comprehensively. What is it that we want really? do we need a whole bunch of visualization? Or is there a single template that all these visualization are following?

**Comment by krs-world** [comment]
David, here is the issue to create new data structures with their names. Can you add them to the server so I can test. We already have a KD-tree element in BRIDGES
