### ISSUE TITLE
Color grid is broken?

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#78]
I cant get the color grid to work properly anymore.. can one of you check. I am pretty sure its related to the RLE, as I see something like an encoded image.

It works on the clone, but no longer works on the live server (C++ version).

       -- krs

**Comment by esaule** [comment]
Indeed, version 2.4 is not compatible with the current bridges-cs server. we need to update the bridges server but did not want to do that while the semester was still going on. We should probably push all updates (to the server and to the codes distributed to the users on the website) during the break.

**Comment by esaule** [comment]
Probably the current java version is broken as well.

**Comment by esaule** [comment]
Is this fixed?

**Comment by krs-world** [comment]
I think this is solved and working.. closing it.
