### ISSUE TITLE
C++  version - static variables.

### ISSUE THREAD

**Issue by krs-world** [krs-world/bridges-cxx#80]
Need to carefully look at use of static variables in the C++ Bridges version. In particular, the Color.h  and Element.h needs attention - using ColorNames which is declared as static.

Also thought Element had an identifier (was declared as static), but has disappeared.

Erik is the best person to clean this mess up!

**Comment by esaule** [comment]
Color::ColorNames is a function that returns the map. This should be fine. Looking at Element.h now.

**Comment by esaule** [comment]
done.
